### ISSUE TITLE
Add techs descriptions bottom sheets on mobile website

### ISSUE THREAD

**Issue by JsonLinesCode** [florian-lefebvre/portfolio#1]
It would be nice to be able to see the techs details on the mobile website as on the desktop website.

**Comment by florian-lefebvre** [comment]
Great idea! A bottom sheet is not adapted for desktop, any idea for large screens ? I'm thinking about a modal but another solution would be better.

**Comment by JsonLinesCode** [comment]
Wasn't there already a dialog on desktop website?

**Comment by florian-lefebvre** [comment]
Yes on the v2 but I'm not satisfied of this modal so I'm searching for better ideas (if they exist).

**Comment by florian-lefebvre** [comment]
I just added description to techs in popovers.
